name: Update data.json

on:
  repository_dispatch:
    types: [update-data]

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Update data.json
        run: |
          echo '${{ github.event.client_payload.newData }}' > data.json

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data.json
          git commit -m "Update data.json via repository_dispatch" || echo "No changes"
          git push
